import { Project, Task } from "@/types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "1",
    name: "DevFlow SaaS Core",
    description: "Arquitetura base, autenticação e gestão de estado do DevFlow.",
    key: "DFC",
    lead: "Paulo Developer",
    tasksCount: 16,
    completedTasks: 12,
    status: "Ativo",
    updatedAt: "Há 10 minutos",
  },
  {
    id: "2",
    name: "Design System & UI Kit",
    description: "Componentes atômicos com Tailwind v4 e suporte a Dark Mode nativo.",
    key: "DSK",
    lead: "Frontend Team",
    tasksCount: 8,
    completedTasks: 5,
    status: "Em progresso",
    updatedAt: "Há 2 horas",
  },
  {
    id: "3",
    name: "Módulo Kanban Drag-and-Drop",
    description: "Visualização ágil de tarefas por colunas com atualização otimista.",
    key: "KAN",
    lead: "Agile Team",
    tasksCount: 14,
    completedTasks: 2,
    status: "Planejado",
    updatedAt: "Ontem",
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    projectId: "1",
    title: "Implementar autenticação com NextAuth / Auth.js",
    status: "in_progress",
    priority: "urgente",
    assignee: { name: "Paulo Developer" },
    dueDate: "Amanhã",
    createdAt: "Hoje",
  },
  {
    id: "task-2",
    projectId: "1",
    title: "Configurar esquema do banco de dados relacional",
    status: "todo",
    priority: "alta",
    assignee: { name: "Backend Team" },
    dueDate: "Em 3 dias",
    createdAt: "Ontem",
  },
  {
    id: "task-3",
    projectId: "2",
    title: "Criar tokens de tema escuro no Tailwind v4",
    status: "done",
    priority: "media",
    assignee: { name: "Design Team" },
    dueDate: "Ontem",
    createdAt: "Há 2 dias",
  },
  {
    id: "task-4",
    projectId: "1",
    title: "Criar layout App Shell com Route Groups",
    status: "done",
    priority: "alta",
    assignee: { name: "Paulo Developer" },
    dueDate: "Hoje",
    createdAt: "Hoje",
  },
];
